name: RC Cut Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
jobs:
  Release-Candidate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Perform Release
        run: |
          mvn release:clean \
            release:prepare \
            release:perform \
            -DpushChanges=true \
            -DlocalCheckout=false \
            -DpreparationGoals="clean verify" \
            -Darguments="-DskipTests"
            -Dgoals=""